Update basics/classes.md
dlang-tour/japanese pull request #121
Opened 2019-05-07 23:43 UTC by kotet

2019-05-08 07:59 UTC, mekaboti requested changes

2019-05-08 07:59 UTC, mekaboti commented on basics/classes.md
> +ガベージコレクタはオブジェクトへの参照が存在しなくなった時にメモリを開放します。
ガベージコレクタはオブジェクトへの参照が存在しなくなった時にメモリが開放されていることを確認します。

2019-05-08 07:59 UTC, mekaboti commented on basics/classes.md
> +これは関数の意図的でないオーバーライドを防止します。
これは関数の意図しないオーバーライドを防止します。

2019-05-08 07:59 UTC, mekaboti commented on basics/classes.md
> +Dでは、クラスはクラスからのみ継承できます。
Dでは、クラスはクラスを一つだけ継承できます。

2019-05-08 07:59 UTC, mekaboti commented on basics/classes.md
> +### Finalとabstractメンバ関数
Finalと抽象メンバ関数 (javaの抽象メソッド　Abstract Methods　より）

2019-05-08 07:59 UTC, mekaboti commented on basics/classes.md
> +- それをインスタンス化させないために、クラス全体を`abstract`として宣言できます
それがインスタンス化されない（されていない？）ことを確かにするために、クラス全体を`abstract`として宣言できます

2019-05-08 07:59 UTC, mekaboti commented on basics/classes.md
> +なんにでも使える手のこんだ型です...
なんにでも使える豪勢な型です　（ref https://kiwi-english.net/19773)

2019-05-08 07:59 UTC, mekaboti commented on basics/classes.md
> +    // ところで、publicは暗黙的です
ちなみに、publicは暗黙的です

2019-05-08 07:59 UTC, mekaboti commented on basics/classes.md
> +    // これは実装される必要があります!
これは別途で実装する必要があります。　（元の訳は直訳感があるので、もう少し自然な訳を付けてあげたほうがいいかと）

2019-05-08 08:06 UTC, kotet commented on basics/classes.md
> +ガベージコレクタはオブジェクトへの参照が存在しなくなった時にメモリを開放します。
メモリを開放するのはガベージコレクタなので「確認します」はおかしい気がします

2019-05-08 08:28 UTC, mekaboti commented on basics/classes.md
> +ガベージコレクタはオブジェクトへの参照が存在しなくなった時にメモリを開放します。
https://tour.dlang.org/tour/en/basics/memoryの一行目、"D is a system programming language and thus allows manual memory management. "を参考にすると、この原文はメモリが手動で開放されることも想定していると考えられます。

2019-05-08 08:42 UTC, kotet commented on basics/classes.md
> +ガベージコレクタはオブジェクトへの参照が存在しなくなった時にメモリを開放します。
手動で管理するメモリにGCが関わることはないと思っていたのですが、ちょっとわからないですね…… @dlang-tour/japanese 詳しい人がいれば意見を聞きたいです

2019-05-08 09:04 UTC, kubo39 commented on basics/classes.md
> +ガベージコレクタはオブジェクトへの参照が存在しなくなった時にメモリを開放します。
「確認します」のところを「確実にしてくれるでしょう」にしたらいいじゃないかな、と。

> メモリを開放するのはガベージコレクタなので「確認します」はおかしい気がします

私もここではメモリを解放する主体はGCだと思うので、「確認します」は奇妙な感じがします。

2019-05-08 09:36 UTC, mekaboti commented on basics/classes.md
> +ガベージコレクタはオブジェクトへの参照が存在しなくなった時にメモリを開放します。
「確実にしてくれるでしょう」という訳は英語的みれば不適切ではないでしょうか？
というのも、 GC will make it sure that  the memory is freed　が「確実にしてくれるでしょう」の訳に対応するはずだからです。（ただGCがメモリ解放をするということだけを考えれば、元の訳でもいい気はしますが...）

2019-05-08 10:22 UTC, kubo39 commented on basics/classes.md
> +ガベージコレクタはオブジェクトへの参照が存在しなくなった時にメモリを開放します。
であれば、最初の訳のままいきましょうか。

2019-05-08 10:43 UTC, mekaboti commented on basics/classes.md
> +ガベージコレクタはオブジェクトへの参照が存在しなくなった時にメモリを開放します。
そうですね　少し引っかかるところはありますが、最初の訳で行きましょう。

2019-05-09 07:48 UTC, mekaboti approved these changes

2019-05-09 07:56 UTC, merged