Translate dub
dlang-tour/japanese pull request #92
Opened 2018-03-02 14:40 UTC by lempiji

english版にあったdubフォルダを日本語に翻訳しました。
mirとpeggedのあたり少し意訳が多いので確認してもらえますでしょうか

2018-03-06 04:08 UTC, kotet requested changes

2018-03-06 04:08 UTC, kotet commented on dub/lubeck.md
> +
ここの改行は不要です

2018-03-06 04:08 UTC, kotet commented on dub/mir-algorithm.md
> +        // 要素の型を浮動小数点であるdouble型に変換し、
"double precision FP numbers"なので「倍精度浮動小数点数」と1単語としたほうがいいと思います

2018-03-10 09:33 UTC, kotet requested changes

2018-03-10 09:33 UTC, kotet commented on dub/lubeck.md
> +
説明不足でした。「〜インストールされています。」と「LinuxやWindowsでは〜」の間の改行です

2018-03-10 09:40 UTC, lempiji commented
直しました！

2018-03-10 09:40 UTC, kotet approved these changes

2018-03-10 09:40 UTC, kotet commented
LGTM!

2018-03-11 11:42 UTC, ZombineDev commented
@kotet feel free to merge this PR, if you think it's ready.

2018-03-11 11:48 UTC, kotet commented
Okey!

2018-03-11 11:48 UTC, merged